Adding grant revoke admin endpoints
WeblateOrg/weblate pull request #10292
Opened 2023-10-27 18:03 UTC by nidhi-kala

Addressing #10222 

This PR will add API endpoints for granting and revoking admin rights.
I have added tests for the endpoints.

## Checklist

- [x] Lint and unit tests pass locally with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added documentation to describe my feature.
- [x] I have described the changes in the commit messages.

2023-11-06 13:15 UTC, nijel reviewed
To be consistent with other similar API endpoints, it should be:

* /admins/ endpoit - GET to list admins, POST to add
* /admins/(int:user_pk)/ - DELETE To delete

See how /components is handled at GroupViewSet.

2023-12-15 23:21 UTC, nidhi-kala commented
Thank you for guiding me @nijel !
I have made the naming consistent for grant and revoke admin endpoints and updated the tests.

2024-01-16 13:25 UTC, nijel requested changes
Thanks, the code looks good, but there are few things which I'd like to see improved:

* The documentation is missing.
* The admins API will not work for group admins, see my comment on permission check.
* Can test for group admin doing changes be added?

2024-01-16 13:25 UTC, nijel commented on weblate/api/views.py
> +        self.perm_check(request)
The perm_check should be extended to optionally accept object, so that group admins can also use this interface.

2024-03-27 10:31 UTC, merged