doc(docker): update docs for docker env vars
WeblateOrg/weblate pull request #5928
Opened 2021-04-27 08:45 UTC by opichon

## Proposed changes

Updated docs for docker environment variables. Specifically added references for `POSTGRES_PASSWORD_FILE`, `WEBLATE_ADMIN_PASSWORD_FILE` and `WEBLATE_EMAIL_HOST_PASSWORD_FILE`.

## Checklist

- [ ] Lint and unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added documentation to describe my feature.
- [ ] I have squashed my commits into logic units.
- [ ] I have described the changes in the commit messages.

## Other information

2021-04-27 11:10 UTC, orangesunny requested changes
I will approve once the suggested small text polishing is done.

@opichon Thank you for the contribution!

2021-04-27 11:10 UTC, orangesunny commented on docs/admin/install/docker.rst
> +    Path to file containing the PostgreSQL password. use as an alternative to POSTGRES_PASSWORD.
Please do a small grammatic correction to:

*Path to the file containing the PostgreSQL password. Use as an alternative to POSTGRES_PASSWORD.*

2021-04-27 11:10 UTC, orangesunny commented on docs/admin/install/docker.rst
> +    Sets the path to a file containing the password for the `admin` user.
please change `a` to `the` file....

2021-04-27 11:10 UTC, orangesunny commented on docs/admin/install/docker.rst
> +    Path to file containing the e-mail authentication password.
Please do a small grammatic correction to:

*Path to the file containing the e-mail authentication password.*

2021-04-27 12:49 UTC, orangesunny commented on docs/admin/install/docker.rst
> +    Path to file containing the PostgreSQL password. use as an alternative to POSTGRES_PASSWORD.
@opichon the article `the` is still missing. Can you copy-paste my suggestion?

2021-04-27 12:50 UTC, orangesunny commented on docs/admin/install/docker.rst
> +    Path to file containing the e-mail authentication password.
Thanks for the implementation!

2021-04-29 15:00 UTC, nijel commented on docs/admin/install/docker.rst
> +    .. seealso::
Please remove trailing line:

```suggestion
    .. seealso::
```

(The pre-commit.ci should automatically fix, but it did timeout this time - https://results.pre-commit.ci/run/github/3559019/1619528947.7e1x1TEpRxeBxI7RoxbL4Q)

2021-04-30 04:38 UTC, merged

2021-04-30 04:38 UTC, nijel commented
Merged, thanks for your contribution!